import type { PharmacyProduct, StoreCategory } from "./types";

export const PLAN_INCLUDES = [
  "Free physician consultation",
  "U.S. licensed pharmacy fulfillment",
  "Discreet temperature-safe shipping",
  "24/7 patient portal support",
];

type ItemInput = Omit<PharmacyProduct, "includes" | "inStock" | "image" | "imageFallback"> & {
  includes?: string[];
  inStock?: boolean;
  image?: string;
  imageFallback?: string;
};

function item(p: ItemInput): PharmacyProduct {
  const defaultImage = `/images/store/${p.slug}.png`;
  return {
    includes: p.includes ?? PLAN_INCLUDES,
    inStock: p.inStock ?? true,
    image: p.image ?? defaultImage,
    imageFallback: p.imageFallback ?? defaultImage,
    ...p,
  };
}

const wl = "weight-loss" as const;
const mh = "mens-health" as const;
const hr = "hair" as const;
const sk = "skincare" as const;
const sw = "sexual-wellness" as const;
const ho = "hormone" as const;

export const PHARMACY_CATALOG: PharmacyProduct[] = [
  // ── Weight Loss (12) ──
  item({
    slug: "tirzepatide-plus",
    name: "Tirzepatide+",
    tagline: "Dual GIP/GLP-1 · Superior metabolic results",
    description: "Weekly dual-pathway injection for appetite control and sustainable weight loss.",
    longDescription: "Our most advanced weight management protocol. Licensed clinicians titrate dosing from your intake, labs, and progress.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 299, compareAtPrice: 389,
    imageAlt: "/images/panel-weight.webp",
    imageAltFallback: "/images/panel-weight.png",
    gallery: ["/images/panel-weight.webp", "/images/result-weight-loss.webp"],
    rating: 4.9, reviews: 2842, features: ["Dual GIP/GLP-1", "Weekly injection", "Provider titration"],
    badge: "Best results", popular: true, peakProduct: "tirzepatide",
  }),
  item({
    slug: "semaglutide-plus",
    name: "Semaglutide+",
    tagline: "GLP-1 · Clinically proven weight loss",
    description: "Physician-guided weekly GLP-1 program with pharmacy fulfillment.",
    longDescription: "Foundational GLP-1 protocol for medical weight management with supplies and ongoing care team messaging.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 146, compareAtPrice: 206,
    imageAlt: "/images/weight-loss-card.webp",
    imageAltFallback: "/images/weight-loss-card.png",
    rating: 4.8, reviews: 3103, features: ["GLP-1 agonist", "Weekly protocol", "Affordable entry"],
    badge: "Most popular", popular: true, peakProduct: "semaglutide",
  }),
  item({
    slug: "liraglutide-daily",
    name: "Liraglutide Daily",
    tagline: "Daily GLP-1 · Flexible dosing",
    description: "Daily injection option for patients who prefer shorter-acting GLP-1 control.",
    longDescription: "Ideal for patients transitioning from other GLP-1 therapies or needing daily dose adjustments.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 179,
    rating: 4.6, reviews: 542, features: ["Daily dosing", "GLP-1", "Flexible titration"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "metabolic-reset",
    name: "Metabolic Reset Program",
    tagline: "GLP-1 + lifestyle coaching",
    description: "Comprehensive program with provider check-ins every 4 weeks.",
    longDescription: "Structured weight-loss journey combining medication options with nutrition guidance.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 189,
    rating: 4.7, reviews: 812, features: ["Multi-phase", "Coach messaging", "Lab optional"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "phentermine-control",
    name: "Phentermine Control",
    tagline: "Appetite suppressant · Short-term boost",
    description: "Prescription appetite support for qualifying patients starting a weight-loss plan.",
    longDescription: "Used alongside lifestyle changes under close physician monitoring for eligible patients.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 89,
    rating: 4.5, reviews: 1204, features: ["Oral daily", "Short-term", "Physician screened"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "contrave-bundle",
    name: "Contrave® Protocol",
    tagline: "Naltrexone/bupropion combination",
    description: "Dual-mechanism oral therapy for chronic weight management.",
    longDescription: "For patients who prefer non-injectable options with proven dual-pathway appetite support.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 129,
    rating: 4.6, reviews: 678, features: ["Oral twice daily", "Non-injection", "Dual pathway"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "wegovy-pathway",
    name: "Wegovy-Compatible Semaglutide",
    tagline: "High-dose GLP-1 pathway",
    description: "Semaglutide protocol aligned with Wegovy® dosing tiers.",
    longDescription: "Physician-guided escalation through standard GLP-1 dose tiers.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 249, compareAtPrice: 329,
    rating: 4.8, reviews: 1456, features: ["Escalating doses", "GLP-1", "Weekly"],
    peakProduct: "semaglutide",
  }),
  item({
    slug: "mounjaro-pathway",
    name: "Mounjaro®-Style Tirzepatide",
    tagline: "Dual agonist · Maximum efficacy",
    description: "Tirzepatide protocol modeled on Mounjaro® dose progression.",
    longDescription: "For patients seeking the strongest available dual GIP/GLP-1 outcomes.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 319, compareAtPrice: 399,
    rating: 4.9, reviews: 987, features: ["Dual agonist", "Dose tiers", "Weekly"],
    peakProduct: "tirzepatide",
  }),
  item({
    slug: "bmi-medical-program",
    name: "BMI Medical Program",
    tagline: "Full metabolic workup",
    description: "Weight program with optional labs and quarterly provider reviews.",
    longDescription: "Comprehensive metabolic screening for patients with BMI ≥ 27 with comorbidities.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 219,
    rating: 4.7, reviews: 445, features: ["Labs optional", "Quarterly review", "Custom plan"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "weight-loss-starter",
    name: "Weight Loss Starter Kit",
    tagline: "Intake + first month supplies",
    description: "Everything needed to begin physician-guided weight management.",
    longDescription: "Includes consultation, medication selection, and first shipment of supplies.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 99, compareAtPrice: 149,
    rating: 4.8, reviews: 2100, features: ["Starter bundle", "Supplies included", "Fast intake"],
    badge: "Starter", newArrival: true, peakCategory: "weight-loss",
  }),
  item({
    slug: "glp1-maintenance",
    name: "GLP-1 Maintenance Plan",
    tagline: "After goal weight · Sustain results",
    description: "Lower-dose maintenance for patients who reached target weight.",
    longDescription: "Ongoing physician oversight at reduced dosing to help sustain long-term results.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 159,
    rating: 4.7, reviews: 534, features: ["Maintenance dose", "Quarterly check", "Portal tracking"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "metabolic-panel-addon",
    name: "Metabolic Lab Panel Add-On",
    tagline: "A1C, lipids, thyroid",
    description: "Optional lab panel to personalize your weight-loss protocol.",
    longDescription: "At-home or local draw options integrated with your treatment plan.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 49,
    rating: 4.6, reviews: 312, features: ["Lab panel", "Add-on", "Personalized dosing"],
    peakCategory: "weight-loss",
  }),

  // ── Men's Health (8) ──
  item({
    slug: "testosterone-trt",
    name: "Testosterone Cypionate",
    tagline: "Gold-standard TRT",
    description: "Restore energy, focus, and drive with hormone replacement.",
    longDescription: "Comprehensive TRT with lab review and refill management.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 120,
    rating: 4.9, reviews: 2240, features: ["TRT", "Labs", "Monthly refills"],
    badge: "Men's #1", popular: true, peakProduct: "testosterone",
  }),
  item({
    slug: "enclomiphene",
    name: "Enclomiphene",
    tagline: "Natural testosterone support",
    description: "Oral alternative to stimulate endogenous testosterone.",
    longDescription: "Popular for younger men with suboptimal levels who prefer non-injection therapy.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 99,
    rating: 4.7, reviews: 645, features: ["Oral", "Fertility-friendly", "Lab-guided"],
    peakProduct: "enclomiphene",
  }),
  item({
    slug: "hcg-trt-support",
    name: "HCG TRT Support",
    tagline: "Fertility · testicular function",
    description: "HCG add-on for men on TRT preserving fertility markers.",
    longDescription: "Often paired with testosterone protocols for testicular function support.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 89,
    rating: 4.6, reviews: 412, features: ["TRT add-on", "Fertility", "Injectable"],
    peakCategory: "mens-health",
  }),
  item({
    slug: "anastrozole-estrogen",
    name: "Anastrozole",
    tagline: "Estrogen management on TRT",
    description: "Aromatase inhibitor for estrogen control during TRT.",
    longDescription: "Prescribed when estradiol elevation occurs on testosterone therapy.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 35,
    rating: 4.5, reviews: 534, features: ["TRT support", "Estrogen control", "Oral"],
    peakCategory: "mens-health",
  }),
  item({
    slug: "dhea-mens",
    name: "DHEA Men's Vitality",
    tagline: "Adrenal hormone precursor",
    description: "DHEA supplementation with lab-monitored dosing.",
    longDescription: "For men with low DHEA-S on labs pursuing vitality support.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 29,
    rating: 4.4, reviews: 289, features: ["Oral daily", "Lab-guided", "Vitality"],
    peakCategory: "mens-health",
  }),
  item({
    slug: "cialis-daily",
    name: "Tadalafil Daily (Cialis®)",
    tagline: "Daily ED · BPH support",
    description: "Low-dose daily tadalafil for ED and urinary symptoms.",
    longDescription: "Same molecule as Cialis® — daily convenience without timing doses.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 45,
    rating: 4.8, reviews: 1867, features: ["Daily", "ED", "BPH option"],
    peakProduct: "tadalafil",
  }),
  item({
    slug: "prostate-support",
    name: "Prostate Support Protocol",
    tagline: "Men's urinary wellness",
    description: "Physician-guided protocol for men's urinary health goals.",
    longDescription: "Includes intake review and medication options where clinically appropriate.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 55,
    rating: 4.5, reviews: 312, features: ["Urinary health", "Men's wellness", "Screening"],
    peakCategory: "mens-health",
  }),
  item({
    slug: "mens-vitality-panel",
    name: "Men's Vitality Lab Panel",
    tagline: "Testosterone · thyroid · metabolic",
    description: "Comprehensive lab panel to guide men's health treatment.",
    longDescription: "At-home or local draw with results reviewed by your provider.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 79,
    rating: 4.7, reviews: 445, features: ["Full panel", "Provider review", "Treatment roadmap"],
    peakCategory: "mens-health",
  }),

  // ── Hair (6) ──
  item({
    slug: "finasteride",
    name: "Finasteride",
    tagline: "DHT blocker",
    description: "Oral treatment to halt male pattern hair loss.",
    longDescription: "Blocks DHT at the follicle with ongoing provider monitoring.",
    category: hr, categoryLabel: "Hair", priceMonthly: 25,
    rating: 4.7, reviews: 2823, features: ["Daily oral", "DHT block", "Proven"],
    peakProduct: "finasteride",
  }),
  item({
    slug: "minoxidil-topical",
    name: "Minoxidil Topical",
    tagline: "Vasodilator · Regrowth",
    description: "Prescription-strength topical for scalp stimulation.",
    longDescription: "Pair with finasteride for dual-action restoration.",
    category: hr, categoryLabel: "Hair", priceMonthly: 39,
    rating: 4.6, reviews: 1502, features: ["Topical", "Twice daily", "Stackable"],
    peakProduct: "minoxidil",
  }),
  item({
    slug: "finasteride-minoxidil-duo",
    name: "Finasteride + Minoxidil Duo",
    tagline: "Dual-action hair system",
    description: "Combined oral + topical for maximum retention and regrowth.",
    longDescription: "Our most complete hair loss program with bundle savings.",
    category: hr, categoryLabel: "Hair", priceMonthly: 49, compareAtPrice: 64,
    rating: 4.8, reviews: 1292, features: ["Dual action", "Bundle", "Provider-guided"],
    badge: "Bundle", popular: true, peakProduct: "finasteride",
  }),
  item({
    slug: "dutasteride",
    name: "Dutasteride",
    tagline: "Stronger DHT block",
    description: "Dual 5-alpha reductase inhibitor for advanced hair loss.",
    longDescription: "For patients who need stronger DHT suppression than finasteride.",
    category: hr, categoryLabel: "Hair", priceMonthly: 35,
    rating: 4.6, reviews: 678, features: ["Strong DHT block", "Oral daily", "Advanced loss"],
    peakCategory: "hair",
  }),
  item({
    slug: "ketoconazole-scalp",
    name: "Ketoconazole Scalp",
    tagline: "Anti-inflammatory scalp care",
    description: "Prescription shampoo for scalp inflammation and thinning.",
    longDescription: "Often added to oral/topical hair protocols.",
    category: hr, categoryLabel: "Hair", priceMonthly: 29,
    rating: 4.5, reviews: 445, features: ["Scalp care", "Anti-inflammatory", "Topical"],
    peakCategory: "hair",
  }),
  item({
    slug: "biotin-hair-growth",
    name: "Biotin Hair Growth+",
    tagline: "Nutraceutical support",
    description: "High-dose biotin with clinician-reviewed dosing.",
    longDescription: "Adjunct support for patients on prescription hair protocols.",
    category: hr, categoryLabel: "Hair", priceMonthly: 19,
    rating: 4.4, reviews: 890, features: ["Biotin", "Adjunct", "Oral"],
    peakCategory: "hair",
  }),

  // ── Skincare (6) ──
  item({
    slug: "tretinoin-005",
    name: "Tretinoin 0.05%",
    tagline: "Prescription retinoid",
    description: "Medical-grade retinoid for anti-aging and acne.",
    longDescription: "Includes purging guidance, SPF protocol, and titration schedule.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 60,
    rating: 4.9, reviews: 3104, features: ["0.05%", "Anti-aging", "Acne"],
    badge: "Top rated", popular: true, peakProduct: "tretinoin",
  }),
  item({
    slug: "anti-aging-cream",
    name: "Custom Anti-Aging Cream",
    tagline: "Compounded skincare",
    description: "Personalized topical for fine lines and texture.",
    longDescription: "Compounded formulation adjusted over time by your clinician.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 55,
    rating: 4.7, reviews: 734, features: ["Custom blend", "Compounded", "Refills"],
    peakCategory: "skincare",
  }),
  item({
    slug: "hydroquinone-brightening",
    name: "Hydroquinone Brightening",
    tagline: "Hyperpigmentation treatment",
    description: "Prescription brightening cream for dark spots and melasma.",
    longDescription: "Cycled protocol with sun protection guidance.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 49,
    rating: 4.6, reviews: 567, features: ["Brightening", "Melasma", "Cycled use"],
    peakCategory: "skincare",
  }),
  item({
    slug: "azelaic-acid",
    name: "Azelaic Acid 15%",
    tagline: "Acne · rosacea · tone",
    description: "Multi-benefit topical for acne, rosacea, and uneven tone.",
    longDescription: "Gentler alternative or complement to retinoids.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 42,
    rating: 4.7, reviews: 892, features: ["Acne", "Rosacea", "Tone"],
    peakCategory: "skincare",
  }),
  item({
    slug: "clindamycin-acne",
    name: "Clindamycin Acne Gel",
    tagline: "Antibiotic topical",
    description: "Prescription gel for inflammatory acne breakouts.",
    longDescription: "Often paired with retinoids in acne protocols.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 35,
    rating: 4.5, reviews: 678, features: ["Acne", "Topical", "Anti-inflammatory"],
    peakCategory: "skincare",
  }),
  item({
    slug: "vitamin-c-protocol",
    name: "Vitamin C + SPF Protocol",
    tagline: "Antioxidant · sun protection",
    description: "Prescription-strength vitamin C with SPF guidance bundle.",
    longDescription: "Complements retinoid therapy for comprehensive skin protection.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 38,
    rating: 4.6, reviews: 445, features: ["Vitamin C", "SPF bundle", "Antioxidant"],
    peakCategory: "skincare",
  }),

  // ── Sexual Wellness (6) ──
  item({
    slug: "sildenafil",
    name: "Sildenafil (Viagra®)",
    tagline: "ED · As-needed",
    description: "Fast-acting ED medication with discreet shipping.",
    longDescription: "Prescribed after confidential intake with dose selection guidance.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 35,
    rating: 4.8, reviews: 3890, features: ["As-needed", "Discreet", "Fast intake"],
    popular: true, peakProduct: "sildenafil",
  }),
  item({
    slug: "tadalafil-daily",
    name: "Tadalafil Daily",
    tagline: "ED · Daily low-dose",
    description: "Daily tadalafil for spontaneity without timing doses.",
    longDescription: "Steady levels for patients who prefer daily convenience.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 45,
    rating: 4.8, reviews: 2567, features: ["Daily", "Spontaneity", "Discreet"],
    peakProduct: "tadalafil",
  }),
  item({
    slug: "tadalafil-as-needed",
    name: "Tadalafil As-Needed",
    tagline: "36-hour window",
    description: "Longer-acting as-needed ED option.",
    longDescription: "Popular for patients wanting extended effectiveness per dose.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 40,
    rating: 4.7, reviews: 1890, features: ["As-needed", "36hr window", "Flexible"],
    peakProduct: "tadalafil",
  }),
  item({
    slug: "ed-starter-bundle",
    name: "ED Starter Bundle",
    tagline: "Sildenafil + Tadalafil trial",
    description: "Try both ED options with physician-guided selection.",
    longDescription: "Find your best fit with provider support on dosing.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 59, compareAtPrice: 80,
    rating: 4.8, reviews: 1234, features: ["Both options", "Trial bundle", "Provider picks"],
    badge: "Bundle", peakCategory: "sexual-wellness",
  }),
  item({
    slug: "pt-141-desire",
    name: "PT-141 (Bremelanotide)",
    tagline: "Desire · arousal support",
    description: "Peptide option for low desire in qualifying patients.",
    longDescription: "FDA-approved mechanism for hypoactive desire in women and men.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 99,
    rating: 4.5, reviews: 534, features: ["Peptide", "Desire", "As directed"],
    peakCategory: "sexual-wellness",
  }),
  item({
    slug: "oxytocin-intimacy",
    name: "Oxytocin Intimacy",
    tagline: "Connection · wellness",
    description: "Compounded oxytocin for intimacy and connection goals.",
    longDescription: "Prescribed for qualifying patients as part of wellness protocols.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 79,
    rating: 4.4, reviews: 312, features: ["Compounded", "Intimacy", "Nasal/spray"],
    peakCategory: "sexual-wellness",
  }),

  // ── Hormone (5) ──
  item({
    slug: "thyroid-levothyroxine",
    name: "Levothyroxine",
    tagline: "Hypothyroidism treatment",
    description: "Thyroid hormone replacement with lab-guided dosing.",
    longDescription: "TSH monitoring and dose adjustments through your portal.",
    category: ho, categoryLabel: "Hormone", priceMonthly: 19,
    rating: 4.8, reviews: 1567, features: ["Thyroid", "Lab-guided", "Daily oral"],
    peakCategory: "hormone",
  }),
  item({
    slug: "armour-thyroid",
    name: "Armour Thyroid®",
    tagline: "Natural desiccated thyroid",
    description: "NDT option for patients preferring natural thyroid hormone.",
    longDescription: "Prescribed when clinically appropriate after lab review.",
    category: ho, categoryLabel: "Hormone", priceMonthly: 35,
    rating: 4.6, reviews: 534, features: ["NDT", "Natural thyroid", "Lab monitored"],
    peakCategory: "hormone",
  }),
  item({
    slug: "pregnenolone",
    name: "Pregnenolone",
    tagline: "Hormone precursor",
    description: "Master hormone precursor with clinician-guided dosing.",
    longDescription: "Part of integrative hormone optimization protocols.",
    category: ho, categoryLabel: "Hormone", priceMonthly: 29,
    rating: 4.4, reviews: 267, features: ["Precursor", "Oral", "Hormone stack"],
    peakCategory: "hormone",
  }),
  item({
    slug: "dhea-womens",
    name: "DHEA Women's Balance",
    tagline: "Adrenal · hormone support",
    description: "DHEA supplementation for women with low DHEA-S on labs.",
    longDescription: "Monitored dosing as part of women's hormone protocols.",
    category: ho, categoryLabel: "Hormone", priceMonthly: 29,
    rating: 4.5, reviews: 389, features: ["Women's", "Lab-guided", "Adrenal"],
    peakCategory: "hormone",
  }),
  item({
    slug: "hormone-full-panel",
    name: "Full Hormone Panel",
    tagline: "Thyroid · sex hormones · adrenal",
    description: "Comprehensive hormone labs with provider interpretation.",
    longDescription: "Foundation for TRT, HRT, and thyroid treatment planning.",
    category: ho, categoryLabel: "Hormone", priceMonthly: 99,
    rating: 4.8, reviews: 612, features: ["Full panel", "All hormones", "Roadmap"],
    peakCategory: "hormone",
  }),
];

export const CATEGORY_LABELS: Record<StoreCategory, string> = {
  "weight-loss": "Weight Loss",
  "mens-health": "Men's Health",
  hair: "Hair",
  skincare: "Skincare",
  "sexual-wellness": "Sexual Wellness",
  hormone: "Hormone",
};
