import type { PharmacyProduct, StoreCategory } from "./types";

export const PLAN_INCLUDES = [
  "Free physician consultation",
  "U.S. licensed pharmacy fulfillment",
  "Discreet temperature-safe shipping",
  "24/7 patient portal support",
];

/** Store image — load JPG (webp is build-only; never requested in the browser). */
export function storeImg(name: string, fallbackExt = "jpg"): { image: string; imageFallback: string } {
  const path = `/images/store/${name}.${fallbackExt}`;
  return { image: path, imageFallback: path };
}

export function brandImg(webp: string, png?: string): { image: string; imageFallback?: string } {
  const image = png ?? webp.replace(/\.webp$/i, ".png");
  return { image, imageFallback: png ?? image };
}

type ItemInput = Omit<PharmacyProduct, "includes" | "inStock"> & {
  includes?: string[];
  inStock?: boolean;
};

function item(p: ItemInput): PharmacyProduct {
  return {
    includes: p.includes ?? PLAN_INCLUDES,
    inStock: p.inStock ?? true,
    ...p,
  };
}

const wl = "weight-loss" as const;
const lg = "longevity" as const;
const rc = "recovery" as const;
const mh = "mens-health" as const;
const wh = "womens-health" as const;
const hr = "hair" as const;
const sk = "skincare" as const;
const sw = "sexual-wellness" as const;
const sl = "sleep" as const;
const mn = "mental-health" as const;
const ho = "hormone" as const;

export const PHARMACY_CATALOG: PharmacyProduct[] = [
  // ── Weight Loss (12) ──
  item({
    slug: "tirzepatide-plus",
    name: "Tirzepatide+",
    tagline: "Dual GIP/GLP-1 · Superior metabolic results",
    description: "Weekly dual-pathway injection for appetite control and sustainable weight loss.",
    longDescription: "Our most advanced weight management protocol. Licensed clinicians titrate dosing from your intake, labs, and progress.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 299, compareAtPrice: 389,
    ...brandImg("/images/tirzepatide-hero.webp", "/images/tirzepatide-hero.png"),
    imageAlt: "/images/panel-weight.webp",
    imageAltFallback: "/images/panel-weight.png",
    gallery: ["/images/panel-weight.webp", "/images/result-weight-loss.webp"],
    rating: 4.9, reviews: 2842, features: ["Dual GIP/GLP-1", "Weekly injection", "Provider titration"],
    badge: "Best results", popular: true, peakProduct: "tirzepatide",
  }),
  item({
    slug: "semaglutide-plus",
    name: "Semaglutide+",
    tagline: "GLP-1 · Clinically proven weight loss",
    description: "Physician-guided weekly GLP-1 program with pharmacy fulfillment.",
    longDescription: "Foundational GLP-1 protocol for medical weight management with supplies and ongoing care team messaging.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 146, compareAtPrice: 206,
    ...brandImg("/images/semaglutide-hero.webp", "/images/semaglutide-hero.png"),
    imageAlt: "/images/weight-loss-card.webp",
    imageAltFallback: "/images/weight-loss-card.png",
    rating: 4.8, reviews: 3103, features: ["GLP-1 agonist", "Weekly protocol", "Affordable entry"],
    badge: "Most popular", popular: true, peakProduct: "semaglutide",
  }),
  item({
    slug: "liraglutide-daily",
    name: "Liraglutide Daily",
    tagline: "Daily GLP-1 · Flexible dosing",
    description: "Daily injection option for patients who prefer shorter-acting GLP-1 control.",
    longDescription: "Ideal for patients transitioning from other GLP-1 therapies or needing daily dose adjustments.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 179,
    ...storeImg("weight-glp1"), rating: 4.6, reviews: 542, features: ["Daily dosing", "GLP-1", "Flexible titration"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "metabolic-reset",
    name: "Metabolic Reset Program",
    tagline: "GLP-1 + lifestyle coaching",
    description: "Comprehensive program with provider check-ins every 4 weeks.",
    longDescription: "Structured weight-loss journey combining medication options with nutrition guidance.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 189,
    ...brandImg("/images/panel-weight.webp", "/images/panel-weight.png"),
    rating: 4.7, reviews: 812, features: ["Multi-phase", "Coach messaging", "Lab optional"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "phentermine-control",
    name: "Phentermine Control",
    tagline: "Appetite suppressant · Short-term boost",
    description: "Prescription appetite support for qualifying patients starting a weight-loss plan.",
    longDescription: "Used alongside lifestyle changes under close physician monitoring for eligible patients.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 89,
    ...storeImg("vitamin-bottles"), rating: 4.5, reviews: 1204, features: ["Oral daily", "Short-term", "Physician screened"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "contrave-bundle",
    name: "Contrave® Protocol",
    tagline: "Naltrexone/bupropion combination",
    description: "Dual-mechanism oral therapy for chronic weight management.",
    longDescription: "For patients who prefer non-injectable options with proven dual-pathway appetite support.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 129,
    ...storeImg("weight-glp1"), rating: 4.6, reviews: 678, features: ["Oral twice daily", "Non-injection", "Dual pathway"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "wegovy-pathway",
    name: "Wegovy-Compatible Semaglutide",
    tagline: "High-dose GLP-1 pathway",
    description: "Semaglutide protocol aligned with Wegovy® dosing tiers.",
    longDescription: "Physician-guided escalation through standard GLP-1 dose tiers.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 249, compareAtPrice: 329,
    ...storeImg("peptide-kit"), rating: 4.8, reviews: 1456, features: ["Escalating doses", "GLP-1", "Weekly"],
    peakProduct: "semaglutide",
  }),
  item({
    slug: "mounjaro-pathway",
    name: "Mounjaro®-Style Tirzepatide",
    tagline: "Dual agonist · Maximum efficacy",
    description: "Tirzepatide protocol modeled on Mounjaro® dose progression.",
    longDescription: "For patients seeking the strongest available dual GIP/GLP-1 outcomes.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 319, compareAtPrice: 399,
    ...storeImg("vial-pharmacy"), rating: 4.9, reviews: 987, features: ["Dual agonist", "Dose tiers", "Weekly"],
    peakProduct: "tirzepatide",
  }),
  item({
    slug: "bmi-medical-program",
    name: "BMI Medical Program",
    tagline: "Full metabolic workup",
    description: "Weight program with optional labs and quarterly provider reviews.",
    longDescription: "Comprehensive metabolic screening for patients with BMI ≥ 27 with comorbidities.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 219,
    ...storeImg("hormone-lab"), rating: 4.7, reviews: 445, features: ["Labs optional", "Quarterly review", "Custom plan"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "weight-loss-starter",
    name: "Weight Loss Starter Kit",
    tagline: "Intake + first month supplies",
    description: "Everything needed to begin physician-guided weight management.",
    longDescription: "Includes consultation, medication selection, and first shipment of supplies.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 99, compareAtPrice: 149,
    ...storeImg("delivery-kit"), rating: 4.8, reviews: 2100, features: ["Starter bundle", "Supplies included", "Fast intake"],
    badge: "Starter", newArrival: true, peakCategory: "weight-loss",
  }),
  item({
    slug: "glp1-maintenance",
    name: "GLP-1 Maintenance Plan",
    tagline: "After goal weight · Sustain results",
    description: "Lower-dose maintenance for patients who reached target weight.",
    longDescription: "Ongoing physician oversight at reduced dosing to help sustain long-term results.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 159,
    ...brandImg("/images/weight-loss-card.webp", "/images/weight-loss-card.png"),
    rating: 4.7, reviews: 534, features: ["Maintenance dose", "Quarterly check", "Portal tracking"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "metabolic-panel-addon",
    name: "Metabolic Lab Panel Add-On",
    tagline: "A1C, lipids, thyroid",
    description: "Optional lab panel to personalize your weight-loss protocol.",
    longDescription: "At-home or local draw options integrated with your treatment plan.",
    category: wl, categoryLabel: "Weight Loss", priceMonthly: 49,
    ...storeImg("hormone-lab"), rating: 4.6, reviews: 312, features: ["Lab panel", "Add-on", "Personalized dosing"],
    peakCategory: "weight-loss",
  }),

  // ── Longevity (10) ──
  item({
    slug: "nad-rejuvenation",
    name: "NAD+ Rejuvenation",
    tagline: "Cellular energy · Anti-aging",
    description: "Physician-supervised NAD+ therapy with medical screening.",
    longDescription: "Replenish NAD+ for energy, focus, and healthy aging with tailored dosing.",
    category: lg, categoryLabel: "Longevity", priceMonthly: 192, compareAtPrice: 249,
    ...brandImg("/images/nad-hero.webp", "/images/nad-hero.png"),
    gallery: ["/images/longevity-card.webp", "/images/panel-nad.webp"],
    rating: 4.8, reviews: 1434, features: ["Cellular energy", "Cognition", "Recovery"],
    badge: "Staff pick", popular: true, peakProduct: "nad",
  }),
  item({
    slug: "nad-oral-boost",
    name: "NAD+ Oral Protocol",
    tagline: "Daily longevity support",
    description: "Oral NAD+ precursor protocol — no injection required.",
    longDescription: "Convenient daily protocol with periodic clinician check-ins.",
    category: lg, categoryLabel: "Longevity", priceMonthly: 149,
    ...storeImg("nad-infusion"), rating: 4.6, reviews: 621, features: ["Daily oral", "No injection", "Longevity"],
    peakCategory: "longevity",
  }),
  item({
    slug: "glutathione-glow",
    name: "Glutathione+",
    tagline: "Master antioxidant",
    description: "Antioxidant protocol for oxidative stress and skin radiance.",
    longDescription: "Supports natural detox pathways — popular add-on to longevity goals.",
    category: lg, categoryLabel: "Longevity", priceMonthly: 129,
    ...brandImg("/images/result-energy.webp", "/images/result-energy.png"),
    rating: 4.5, reviews: 518, features: ["Antioxidant", "Skin support", "Detox"],
    peakProduct: "glutathione",
  }),
  item({
    slug: "nmn-cellular",
    name: "NMN Cellular Boost",
    tagline: "NAD+ precursor · Oral",
    description: "Nicotinamide mononucleotide for cellular NAD+ support.",
    longDescription: "Daily oral longevity supplement with physician intake review.",
    category: lg, categoryLabel: "Longevity", priceMonthly: 119,
    ...storeImg("supplements"), rating: 4.6, reviews: 892, features: ["NMN", "Oral daily", "Energy"],
    peakCategory: "longevity",
  }),
  item({
    slug: "metformin-longevity",
    name: "Metformin Longevity",
    tagline: "AMPK activation · Metabolic aging",
    description: "Off-label longevity protocol for qualifying adults.",
    longDescription: "Popular in longevity medicine for metabolic and cellular aging support.",
    category: lg, categoryLabel: "Longevity", priceMonthly: 39,
    ...storeImg("vitamin-bottles"), rating: 4.5, reviews: 1102, features: ["Oral daily", "Metabolic", "Longevity research"],
    peakCategory: "longevity",
  }),
  item({
    slug: "resveratrol-protocol",
    name: "Resveratrol Protocol",
    tagline: "Sirtuin support",
    description: "High-purity resveratrol with clinician-guided dosing.",
    longDescription: "Part of comprehensive longevity stacks for cellular health.",
    category: lg, categoryLabel: "Longevity", priceMonthly: 59,
    ...storeImg("wellness-tea"), rating: 4.4, reviews: 334, features: ["Antioxidant", "Oral", "Stackable"],
    peakCategory: "longevity",
  }),
  item({
    slug: "coq10-energy",
    name: "CoQ10 Energy+",
    tagline: "Mitochondrial support",
    description: "Coenzyme Q10 for heart and cellular energy production.",
    longDescription: "Especially popular for patients over 40 pursuing longevity goals.",
    category: lg, categoryLabel: "Longevity", priceMonthly: 45,
    ...storeImg("spa-wellness"), rating: 4.5, reviews: 445, features: ["Mitochondrial", "Heart health", "Oral"],
    peakCategory: "longevity",
  }),
  item({
    slug: "longevity-stack-bundle",
    name: "Longevity Stack Bundle",
    tagline: "NAD+ · Glutathione · NMN",
    description: "Three-program bundle for comprehensive cellular support.",
    longDescription: "Save vs. individual programs with unified physician oversight.",
    category: lg, categoryLabel: "Longevity", priceMonthly: 349, compareAtPrice: 420,
    ...storeImg("hormone-lab"), rating: 4.8, reviews: 267, features: ["3-in-1 bundle", "Unified care", "Savings"],
    badge: "Bundle", peakCategory: "longevity",
  }),
  item({
    slug: "epithalon-peptide",
    name: "Epithalon Peptide",
    tagline: "Telomere research peptide",
    description: "Advanced peptide protocol for longevity-focused patients.",
    longDescription: "Prescribed after thorough medical history review.",
    category: lg, categoryLabel: "Longevity", priceMonthly: 169,
    ...storeImg("peptide-kit"), rating: 4.5, reviews: 198, features: ["Peptide", "Advanced", "Cycling protocol"],
    peakCategory: "longevity",
  }),
  item({
    slug: "thymosin-alpha",
    name: "Thymosin Alpha-1",
    tagline: "Immune · longevity peptide",
    description: "Immune-modulating peptide for wellness-focused adults.",
    longDescription: "Used in integrative longevity protocols under physician guidance.",
    category: lg, categoryLabel: "Longevity", priceMonthly: 149,
    ...storeImg("vial-pharmacy"), rating: 4.4, reviews: 156, features: ["Immune support", "Peptide", "Injectable"],
    peakCategory: "longevity",
  }),

  // ── Recovery (8) ──
  item({
    slug: "sermorelin-recovery",
    name: "Sermorelin Recovery",
    tagline: "GH secretagogue · Sleep & lean mass",
    description: "Peptide for recovery, sleep quality, and performance.",
    longDescription: "Stimulates natural GH production with clinician-guided dosing.",
    category: rc, categoryLabel: "Muscle Recovery", priceMonthly: 192,
    ...brandImg("/images/sermorelin-hero.webp", "/images/sermorelin-hero.png"),
    rating: 4.8, reviews: 1056, features: ["Daily peptide", "Sleep", "Lean mass"],
    popular: true, peakProduct: "sermorelin",
  }),
  item({
    slug: "bpc-157-repair",
    name: "BPC-157 Repair",
    tagline: "Tissue repair peptide",
    description: "Advanced peptide for injury recovery and joint health.",
    longDescription: "Popular with athletes seeking accelerated tissue repair.",
    category: rc, categoryLabel: "Muscle Recovery", priceMonthly: 119,
    ...storeImg("bpc-vial"), rating: 4.7, reviews: 802, features: ["Repair", "Joint support", "Athlete-friendly"],
    peakProduct: "bpc-157",
  }),
  item({
    slug: "cjc-ipamorelin",
    name: "CJC-1295 / Ipamorelin",
    tagline: "GH stack · Deep recovery",
    description: "Synergistic peptide stack for body composition and sleep.",
    longDescription: "Prescribed after medical review for recovery and performance goals.",
    category: rc, categoryLabel: "Muscle Recovery", priceMonthly: 139,
    ...brandImg("/images/muscle-recovery-card.webp", "/images/muscle-recovery-card.png"),
    rating: 4.6, reviews: 589, features: ["GH stack", "Night dosing", "Body comp"],
    peakCategory: "muscle-recovery",
  }),
  item({
    slug: "tb-500-recovery",
    name: "TB-500 Recovery",
    tagline: "Systemic tissue repair",
    description: "Thymosin beta-4 analog for systemic recovery support.",
    longDescription: "Used in advanced recovery protocols for soft tissue healing.",
    category: rc, categoryLabel: "Muscle Recovery", priceMonthly: 159,
    ...storeImg("recovery-peptide"), rating: 4.6, reviews: 412, features: ["Systemic repair", "Peptide", "Cycling"],
    peakCategory: "muscle-recovery",
  }),
  item({
    slug: "ghk-cu-tissue",
    name: "GHK-Cu Copper Peptide",
    tagline: "Skin · tissue remodeling",
    description: "Copper peptide for tissue remodeling and skin repair.",
    longDescription: "Injectable or topical options based on treatment goals.",
    category: rc, categoryLabel: "Muscle Recovery", priceMonthly: 99,
    ...storeImg("skincare-cream"), rating: 4.5, reviews: 334, features: ["Copper peptide", "Remodeling", "Skin + tissue"],
    peakCategory: "muscle-recovery",
  }),
  item({
    slug: "joint-recovery-stack",
    name: "Joint Recovery Stack",
    tagline: "BPC-157 + TB-500",
    description: "Dual-peptide bundle for joint and tendon support.",
    longDescription: "Combined protocol for active patients with recurring joint stress.",
    category: rc, categoryLabel: "Muscle Recovery", priceMonthly: 229, compareAtPrice: 278,
    ...storeImg("joint-health"), rating: 4.7, reviews: 278, features: ["Dual peptide", "Joint focus", "Bundle savings"],
    badge: "Bundle", peakCategory: "muscle-recovery",
  }),
  item({
    slug: "athlete-recovery-stack",
    name: "Athlete Recovery Stack",
    tagline: "Sermorelin + BPC-157",
    description: "Performance recovery bundle for training athletes.",
    longDescription: "Physician-supervised stack for training recovery and sleep.",
    category: rc, categoryLabel: "Muscle Recovery", priceMonthly: 279, compareAtPrice: 311,
    ...storeImg("yoga-recovery"), rating: 4.8, reviews: 445, features: ["Performance", "Dual program", "Training"],
    peakCategory: "muscle-recovery",
  }),
  item({
    slug: "pt-141-performance",
    name: "PT-141 Performance",
    tagline: "Recovery · vitality peptide",
    description: "Peptide protocol supporting vitality and recovery goals.",
    longDescription: "Prescribed for qualifying patients as part of wellness protocols.",
    category: rc, categoryLabel: "Muscle Recovery", priceMonthly: 129,
    ...storeImg("supplements"), rating: 4.5, reviews: 267, features: ["Peptide", "Vitality", "As directed"],
    peakCategory: "muscle-recovery",
  }),

  // ── Men's Health (8) ──
  item({
    slug: "testosterone-trt",
    name: "Testosterone Cypionate",
    tagline: "Gold-standard TRT",
    description: "Restore energy, focus, and drive with hormone replacement.",
    longDescription: "Comprehensive TRT with lab review and refill management.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 120,
    ...storeImg("trt-kit"), rating: 4.9, reviews: 2240, features: ["TRT", "Labs", "Monthly refills"],
    badge: "Men's #1", popular: true, peakProduct: "testosterone",
  }),
  item({
    slug: "enclomiphene",
    name: "Enclomiphene",
    tagline: "Natural testosterone support",
    description: "Oral alternative to stimulate endogenous testosterone.",
    longDescription: "Popular for younger men with suboptimal levels who prefer non-injection therapy.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 99,
    ...storeImg("mens-wellness"), rating: 4.7, reviews: 645, features: ["Oral", "Fertility-friendly", "Lab-guided"],
    peakProduct: "enclomiphene",
  }),
  item({
    slug: "hcg-trt-support",
    name: "HCG TRT Support",
    tagline: "Fertility · testicular function",
    description: "HCG add-on for men on TRT preserving fertility markers.",
    longDescription: "Often paired with testosterone protocols for testicular function support.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 89,
    ...storeImg("hormone-lab"), rating: 4.6, reviews: 412, features: ["TRT add-on", "Fertility", "Injectable"],
    peakCategory: "mens-health",
  }),
  item({
    slug: "anastrozole-estrogen",
    name: "Anastrozole",
    tagline: "Estrogen management on TRT",
    description: "Aromatase inhibitor for estrogen control during TRT.",
    longDescription: "Prescribed when estradiol elevation occurs on testosterone therapy.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 35,
    ...storeImg("vitamin-bottles"), rating: 4.5, reviews: 534, features: ["TRT support", "Estrogen control", "Oral"],
    peakCategory: "mens-health",
  }),
  item({
    slug: "dhea-mens",
    name: "DHEA Men's Vitality",
    tagline: "Adrenal hormone precursor",
    description: "DHEA supplementation with lab-monitored dosing.",
    longDescription: "For men with low DHEA-S on labs pursuing vitality support.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 29,
    ...storeImg("supplements"), rating: 4.4, reviews: 289, features: ["Oral daily", "Lab-guided", "Vitality"],
    peakCategory: "mens-health",
  }),
  item({
    slug: "cialis-daily",
    name: "Tadalafil Daily (Cialis®)",
    tagline: "Daily ED · BPH support",
    description: "Low-dose daily tadalafil for ED and urinary symptoms.",
    longDescription: "Same molecule as Cialis® — daily convenience without timing doses.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 45,
    ...storeImg("delivery-kit"), rating: 4.8, reviews: 1867, features: ["Daily", "ED", "BPH option"],
    peakProduct: "tadalafil",
  }),
  item({
    slug: "prostate-support",
    name: "Prostate Support Protocol",
    tagline: "Men's urinary wellness",
    description: "Physician-guided protocol for men's urinary health goals.",
    longDescription: "Includes intake review and medication options where clinically appropriate.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 55,
    ...storeImg("fitness-man"), rating: 4.5, reviews: 312, features: ["Urinary health", "Men's wellness", "Screening"],
    peakCategory: "mens-health",
  }),
  item({
    slug: "mens-vitality-panel",
    name: "Men's Vitality Lab Panel",
    tagline: "Testosterone · thyroid · metabolic",
    description: "Comprehensive lab panel to guide men's health treatment.",
    longDescription: "At-home or local draw with results reviewed by your provider.",
    category: mh, categoryLabel: "Men's Health", priceMonthly: 79,
    ...storeImg("hormone-lab"), rating: 4.7, reviews: 445, features: ["Full panel", "Provider review", "Treatment roadmap"],
    peakCategory: "mens-health",
  }),

  // ── Women's Health (6) ──
  item({
    slug: "bioidentical-hrt",
    name: "Bioidentical HRT",
    tagline: "Personalized hormone therapy",
    description: "Custom-compounded bioidentical hormones for menopause support.",
    longDescription: "Dosing tailored from symptoms, history, and lab results.",
    category: wh, categoryLabel: "Women's Health", priceMonthly: 149,
    ...storeImg("womens-wellness"), rating: 4.8, reviews: 934, features: ["Bioidentical", "Compounded", "Personalized"],
    badge: "Women's #1", popular: true, peakCategory: "hormone",
  }),
  item({
    slug: "progesterone-bioidentical",
    name: "Progesterone Bioidentical",
    tagline: "Sleep · cycle · menopause",
    description: "Micronized progesterone for perimenopause and menopause.",
    longDescription: "Often paired with estradiol in balanced HRT protocols.",
    category: wh, categoryLabel: "Women's Health", priceMonthly: 69,
    ...storeImg("skincare-cream"), rating: 4.7, reviews: 612, features: ["Bioidentical", "Oral/topical", "Cycle support"],
    peakCategory: "hormone",
  }),
  item({
    slug: "estradiol-patch",
    name: "Estradiol Patch",
    tagline: "Transdermal estrogen",
    description: "Weekly patch option for steady estrogen delivery.",
    longDescription: "Popular transdermal option with fewer daily pills.",
    category: wh, categoryLabel: "Women's Health", priceMonthly: 89,
    ...storeImg("delivery-kit"), rating: 4.7, reviews: 534, features: ["Transdermal", "Weekly patch", "Steady levels"],
    peakCategory: "hormone",
  }),
  item({
    slug: "pcos-metformin",
    name: "PCOS Metformin Protocol",
    tagline: "Insulin sensitivity · PCOS",
    description: "Metformin protocol for PCOS-related metabolic goals.",
    longDescription: "Physician-guided dosing for qualifying women with PCOS.",
    category: wh, categoryLabel: "Women's Health", priceMonthly: 39,
    ...storeImg("supplements"), rating: 4.6, reviews: 789, features: ["PCOS", "Metabolic", "Oral daily"],
    peakCategory: "weight-loss",
  }),
  item({
    slug: "womens-hormone-panel",
    name: "Women's Hormone Panel",
    tagline: "Estradiol · progesterone · thyroid",
    description: "Comprehensive hormone labs with provider interpretation.",
    longDescription: "Foundation for personalized women's health treatment plans.",
    category: wh, categoryLabel: "Women's Health", priceMonthly: 89,
    ...storeImg("hormone-lab"), rating: 4.8, reviews: 445, features: ["Lab panel", "Hormone map", "Provider review"],
    peakCategory: "hormone",
  }),
  item({
    slug: "womens-weight-program",
    name: "Women's Weight Program",
    tagline: "GLP-1 · hormone-aware dosing",
    description: "Weight management designed for women's hormonal context.",
    longDescription: "Considers cycle, menopause status, and thyroid in treatment planning.",
    category: wh, categoryLabel: "Women's Health", priceMonthly: 169,
    ...brandImg("/images/patient-result-03.webp", "/images/patient-result-03.png"),
    rating: 4.8, reviews: 1123, features: ["Women-specific", "GLP-1 option", "Hormone-aware"],
    peakCategory: "weight-loss",
  }),

  // ── Hair (6) ──
  item({
    slug: "finasteride",
    name: "Finasteride",
    tagline: "DHT blocker",
    description: "Oral treatment to halt male pattern hair loss.",
    longDescription: "Blocks DHT at the follicle with ongoing provider monitoring.",
    category: hr, categoryLabel: "Hair", priceMonthly: 25,
    ...storeImg("vitamin-bottles"), rating: 4.7, reviews: 2823, features: ["Daily oral", "DHT block", "Proven"],
    peakProduct: "finasteride",
  }),
  item({
    slug: "minoxidil-topical",
    name: "Minoxidil Topical",
    tagline: "Vasodilator · Regrowth",
    description: "Prescription-strength topical for scalp stimulation.",
    longDescription: "Pair with finasteride for dual-action restoration.",
    category: hr, categoryLabel: "Hair", priceMonthly: 39,
    ...storeImg("hair-treatment"), rating: 4.6, reviews: 1502, features: ["Topical", "Twice daily", "Stackable"],
    peakProduct: "minoxidil",
  }),
  item({
    slug: "finasteride-minoxidil-duo",
    name: "Finasteride + Minoxidil Duo",
    tagline: "Dual-action hair system",
    description: "Combined oral + topical for maximum retention and regrowth.",
    longDescription: "Our most complete hair loss program with bundle savings.",
    category: hr, categoryLabel: "Hair", priceMonthly: 49, compareAtPrice: 64,
    ...storeImg("hair-treatment"), rating: 4.8, reviews: 1292, features: ["Dual action", "Bundle", "Provider-guided"],
    badge: "Bundle", popular: true, peakProduct: "finasteride",
  }),
  item({
    slug: "dutasteride",
    name: "Dutasteride",
    tagline: "Stronger DHT block",
    description: "Dual 5-alpha reductase inhibitor for advanced hair loss.",
    longDescription: "For patients who need stronger DHT suppression than finasteride.",
    category: hr, categoryLabel: "Hair", priceMonthly: 35,
    ...storeImg("hair-treatment"), rating: 4.6, reviews: 678, features: ["Strong DHT block", "Oral daily", "Advanced loss"],
    peakCategory: "hair",
  }),
  item({
    slug: "ketoconazole-scalp",
    name: "Ketoconazole Scalp",
    tagline: "Anti-inflammatory scalp care",
    description: "Prescription shampoo for scalp inflammation and thinning.",
    longDescription: "Often added to oral/topical hair protocols.",
    category: hr, categoryLabel: "Hair", priceMonthly: 29,
    ...storeImg("hair-treatment"), rating: 4.5, reviews: 445, features: ["Scalp care", "Anti-inflammatory", "Topical"],
    peakCategory: "hair",
  }),
  item({
    slug: "biotin-hair-growth",
    name: "Biotin Hair Growth+",
    tagline: "Nutraceutical support",
    description: "High-dose biotin with clinician-reviewed dosing.",
    longDescription: "Adjunct support for patients on prescription hair protocols.",
    category: hr, categoryLabel: "Hair", priceMonthly: 19,
    ...storeImg("vitamin-bottles"), rating: 4.4, reviews: 890, features: ["Biotin", "Adjunct", "Oral"],
    peakCategory: "hair",
  }),

  // ── Skincare (6) ──
  item({
    slug: "tretinoin-005",
    name: "Tretinoin 0.05%",
    tagline: "Prescription retinoid",
    description: "Medical-grade retinoid for anti-aging and acne.",
    longDescription: "Includes purging guidance, SPF protocol, and titration schedule.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 60,
    ...storeImg("skincare-cream"), rating: 4.9, reviews: 3104, features: ["0.05%", "Anti-aging", "Acne"],
    badge: "Top rated", popular: true, peakProduct: "tretinoin",
  }),
  item({
    slug: "anti-aging-cream",
    name: "Custom Anti-Aging Cream",
    tagline: "Compounded skincare",
    description: "Personalized topical for fine lines and texture.",
    longDescription: "Compounded formulation adjusted over time by your clinician.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 55,
    ...storeImg("skincare-cream"), rating: 4.7, reviews: 734, features: ["Custom blend", "Compounded", "Refills"],
    peakCategory: "skincare",
  }),
  item({
    slug: "hydroquinone-brightening",
    name: "Hydroquinone Brightening",
    tagline: "Hyperpigmentation treatment",
    description: "Prescription brightening cream for dark spots and melasma.",
    longDescription: "Cycled protocol with sun protection guidance.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 49,
    ...storeImg("skincare-cream"), rating: 4.6, reviews: 567, features: ["Brightening", "Melasma", "Cycled use"],
    peakCategory: "skincare",
  }),
  item({
    slug: "azelaic-acid",
    name: "Azelaic Acid 15%",
    tagline: "Acne · rosacea · tone",
    description: "Multi-benefit topical for acne, rosacea, and uneven tone.",
    longDescription: "Gentler alternative or complement to retinoids.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 42,
    ...storeImg("skincare-cream"), rating: 4.7, reviews: 892, features: ["Acne", "Rosacea", "Tone"],
    peakCategory: "skincare",
  }),
  item({
    slug: "clindamycin-acne",
    name: "Clindamycin Acne Gel",
    tagline: "Antibiotic topical",
    description: "Prescription gel for inflammatory acne breakouts.",
    longDescription: "Often paired with retinoids in acne protocols.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 35,
    ...storeImg("skincare-cream"), rating: 4.5, reviews: 678, features: ["Acne", "Topical", "Anti-inflammatory"],
    peakCategory: "skincare",
  }),
  item({
    slug: "vitamin-c-protocol",
    name: "Vitamin C + SPF Protocol",
    tagline: "Antioxidant · sun protection",
    description: "Prescription-strength vitamin C with SPF guidance bundle.",
    longDescription: "Complements retinoid therapy for comprehensive skin protection.",
    category: sk, categoryLabel: "Skincare", priceMonthly: 38,
    ...storeImg("skincare-cream"), rating: 4.6, reviews: 445, features: ["Vitamin C", "SPF bundle", "Antioxidant"],
    peakCategory: "skincare",
  }),

  // ── Sexual Wellness (6) ──
  item({
    slug: "sildenafil",
    name: "Sildenafil (Viagra®)",
    tagline: "ED · As-needed",
    description: "Fast-acting ED medication with discreet shipping.",
    longDescription: "Prescribed after confidential intake with dose selection guidance.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 35,
    ...storeImg("delivery-kit"), rating: 4.8, reviews: 3890, features: ["As-needed", "Discreet", "Fast intake"],
    popular: true, peakProduct: "sildenafil",
  }),
  item({
    slug: "tadalafil-daily",
    name: "Tadalafil Daily",
    tagline: "ED · Daily low-dose",
    description: "Daily tadalafil for spontaneity without timing doses.",
    longDescription: "Steady levels for patients who prefer daily convenience.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 45,
    ...storeImg("sexual-wellness"), rating: 4.8, reviews: 2567, features: ["Daily", "Spontaneity", "Discreet"],
    peakProduct: "tadalafil",
  }),
  item({
    slug: "tadalafil-as-needed",
    name: "Tadalafil As-Needed",
    tagline: "36-hour window",
    description: "Longer-acting as-needed ED option.",
    longDescription: "Popular for patients wanting extended effectiveness per dose.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 40,
    ...storeImg("delivery-kit"), rating: 4.7, reviews: 1890, features: ["As-needed", "36hr window", "Flexible"],
    peakProduct: "tadalafil",
  }),
  item({
    slug: "ed-starter-bundle",
    name: "ED Starter Bundle",
    tagline: "Sildenafil + Tadalafil trial",
    description: "Try both ED options with physician-guided selection.",
    longDescription: "Find your best fit with provider support on dosing.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 59, compareAtPrice: 80,
    ...storeImg("sexual-wellness"), rating: 4.8, reviews: 1234, features: ["Both options", "Trial bundle", "Provider picks"],
    badge: "Bundle", peakCategory: "sexual-wellness",
  }),
  item({
    slug: "pt-141-desire",
    name: "PT-141 (Bremelanotide)",
    tagline: "Desire · arousal support",
    description: "Peptide option for low desire in qualifying patients.",
    longDescription: "FDA-approved mechanism for hypoactive desire in women and men.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 99,
    ...storeImg("spa-wellness"), rating: 4.5, reviews: 534, features: ["Peptide", "Desire", "As directed"],
    peakCategory: "sexual-wellness",
  }),
  item({
    slug: "oxytocin-intimacy",
    name: "Oxytocin Intimacy",
    tagline: "Connection · wellness",
    description: "Compounded oxytocin for intimacy and connection goals.",
    longDescription: "Prescribed for qualifying patients as part of wellness protocols.",
    category: sw, categoryLabel: "Sexual Wellness", priceMonthly: 79,
    ...storeImg("meditation"), rating: 4.4, reviews: 312, features: ["Compounded", "Intimacy", "Nasal/spray"],
    peakCategory: "sexual-wellness",
  }),

  // ── Sleep (5) ──
  item({
    slug: "melatonin-sleep",
    name: "Melatonin Sleep Protocol",
    tagline: "Circadian reset",
    description: "Physician-guided melatonin for sleep rhythm support.",
    longDescription: "Includes sleep history intake and dosing protocol.",
    category: sl, categoryLabel: "Sleep", priceMonthly: 29,
    ...storeImg("melatonin-bottle"), rating: 4.5, reviews: 978, features: ["Circadian", "Non-habit forming", "Guided dose"],
    peakProduct: "melatonin",
  }),
  item({
    slug: "trazodone-sleep",
    name: "Trazodone Sleep",
    tagline: "Prescription sleep support",
    description: "Low-dose trazodone for patients with persistent insomnia.",
    longDescription: "Prescribed after screening for interactions and sleep history.",
    category: sl, categoryLabel: "Sleep", priceMonthly: 25,
    ...storeImg("sleep-rest"), rating: 4.6, reviews: 1123, features: ["Prescription", "Low dose", "Insomnia"],
    peakCategory: "sleep",
  }),
  item({
    slug: "magnesium-glycinate",
    name: "Magnesium Glycinate",
    tagline: "Relaxation · sleep quality",
    description: "High-absorption magnesium for sleep and muscle relaxation.",
    longDescription: "Popular nutraceutical add-on to sleep protocols.",
    category: sl, categoryLabel: "Sleep", priceMonthly: 19,
    ...storeImg("supplements"), rating: 4.5, reviews: 756, features: ["Magnesium", "Relaxation", "Oral nightly"],
    peakCategory: "sleep",
  }),
  item({
    slug: "sleep-consultation",
    name: "Sleep Medicine Consultation",
    tagline: "Insomnia · sleep hygiene",
    description: "Provider review for chronic sleep difficulties.",
    longDescription: "Comprehensive sleep intake with personalized treatment recommendations.",
    category: sl, categoryLabel: "Sleep", priceMonthly: 0,
    ...storeImg("professional-woman"), rating: 4.9, reviews: 445, features: ["Free consult", "Sleep intake", "Custom plan"],
    badge: "Free consult", peakCategory: "sleep",
  }),
  item({
    slug: "cbn-sleep",
    name: "CBN Sleep Support",
    tagline: "Cannabinoid sleep aid",
    description: "Compounded CBN protocol where legally permitted.",
    longDescription: "Available in qualifying states after physician review.",
    category: sl, categoryLabel: "Sleep", priceMonthly: 49,
    ...storeImg("sleep-rest"), rating: 4.4, reviews: 289, features: ["CBN", "State-dependent", "Compounded"],
    peakCategory: "sleep",
  }),

  // ── Mental Health (5) ──
  item({
    slug: "sertraline-anxiety",
    name: "Sertraline (Zoloft®)",
    tagline: "Anxiety · depression",
    description: "SSRI for anxiety and depression with telehealth follow-ups.",
    longDescription: "Ongoing medication management through your patient portal.",
    category: mn, categoryLabel: "Mental Health", priceMonthly: 25,
    ...storeImg("mental-calm"), rating: 4.7, reviews: 2340, features: ["SSRI", "Anxiety", "Depression"],
    peakCategory: "mental-health",
  }),
  item({
    slug: "escitalopram-mood",
    name: "Escitalopram (Lexapro®)",
    tagline: "Mood · anxiety support",
    description: "SSRI option for generalized anxiety and mood support.",
    longDescription: "Prescribed after mental health intake and medical history review.",
    category: mn, categoryLabel: "Mental Health", priceMonthly: 25,
    ...storeImg("brain-focus"), rating: 4.7, reviews: 1890, features: ["SSRI", "Mood", "Anxiety"],
    peakCategory: "mental-health",
  }),
  item({
    slug: "buspirone-stress",
    name: "Buspirone",
    tagline: "Non-addictive anxiety",
    description: "Anti-anxiety option without benzodiazepine dependence risk.",
    longDescription: "For patients seeking non-controlled anxiety support.",
    category: mn, categoryLabel: "Mental Health", priceMonthly: 22,
    ...storeImg("meditation"), rating: 4.5, reviews: 678, features: ["Non-controlled", "Anxiety", "Daily oral"],
    peakCategory: "mental-health",
  }),
  item({
    slug: "mental-health-intake",
    name: "Mental Health Intake",
    tagline: "Start treatment today",
    description: "Confidential intake with licensed provider review.",
    longDescription: "Gateway to medication management and ongoing telehealth care.",
    category: mn, categoryLabel: "Mental Health", priceMonthly: 0,
    ...storeImg("professional-woman"), rating: 4.9, reviews: 890, features: ["Free intake", "Confidential", "Licensed provider"],
    badge: "Free consult", peakCategory: "mental-health",
  }),
  item({
    slug: "wellbutrin-energy",
    name: "Bupropion (Wellbutrin®)",
    tagline: "Energy · mood · smoking",
    description: "NDRI for depression with energizing profile.",
    longDescription: "Also used for smoking cessation in qualifying patients.",
    category: mn, categoryLabel: "Mental Health", priceMonthly: 28,
    ...storeImg("supplements"), rating: 4.6, reviews: 1123, features: ["NDRI", "Energizing", "Smoking cessation"],
    peakCategory: "mental-health",
  }),

  // ── Hormone (5) ──
  item({
    slug: "thyroid-levothyroxine",
    name: "Levothyroxine",
    tagline: "Hypothyroidism treatment",
    description: "Thyroid hormone replacement with lab-guided dosing.",
    longDescription: "TSH monitoring and dose adjustments through your portal.",
    category: ho, categoryLabel: "Hormone", priceMonthly: 19,
    ...storeImg("hormone-lab"), rating: 4.8, reviews: 1567, features: ["Thyroid", "Lab-guided", "Daily oral"],
    peakCategory: "hormone",
  }),
  item({
    slug: "armour-thyroid",
    name: "Armour Thyroid®",
    tagline: "Natural desiccated thyroid",
    description: "NDT option for patients preferring natural thyroid hormone.",
    longDescription: "Prescribed when clinically appropriate after lab review.",
    category: ho, categoryLabel: "Hormone", priceMonthly: 35,
    ...storeImg("hormone-lab"), rating: 4.6, reviews: 534, features: ["NDT", "Natural thyroid", "Lab monitored"],
    peakCategory: "hormone",
  }),
  item({
    slug: "pregnenolone",
    name: "Pregnenolone",
    tagline: "Hormone precursor",
    description: "Master hormone precursor with clinician-guided dosing.",
    longDescription: "Part of integrative hormone optimization protocols.",
    category: ho, categoryLabel: "Hormone", priceMonthly: 29,
    ...storeImg("vitamin-bottles"), rating: 4.4, reviews: 267, features: ["Precursor", "Oral", "Hormone stack"],
    peakCategory: "hormone",
  }),
  item({
    slug: "dhea-womens",
    name: "DHEA Women's Balance",
    tagline: "Adrenal · hormone support",
    description: "DHEA supplementation for women with low DHEA-S on labs.",
    longDescription: "Monitored dosing as part of women's hormone protocols.",
    category: ho, categoryLabel: "Hormone", priceMonthly: 29,
    ...storeImg("womens-wellness"), rating: 4.5, reviews: 389, features: ["Women's", "Lab-guided", "Adrenal"],
    peakCategory: "hormone",
  }),
  item({
    slug: "hormone-full-panel",
    name: "Full Hormone Panel",
    tagline: "Thyroid · sex hormones · adrenal",
    description: "Comprehensive hormone labs with provider interpretation.",
    longDescription: "Foundation for TRT, HRT, and thyroid treatment planning.",
    category: ho, categoryLabel: "Hormone", priceMonthly: 99,
    ...storeImg("hormone-lab"), rating: 4.8, reviews: 612, features: ["Full panel", "All hormones", "Roadmap"],
    peakCategory: "hormone",
  }),

  // ── Consultation / Gateway ──
  item({
    slug: "physician-consultation",
    name: "Physician Consultation",
    tagline: "Start any program",
    description: "Not sure which treatment fits? Begin with a licensed consult.",
    longDescription: "Your clinician reviews goals and history, then recommends the right program. Only charged if prescribed.",
    category: lg, categoryLabel: "Consultation", priceMonthly: 0,
    ...storeImg("professional-woman"),
    gallery: ["/images/step-03-provider-review.webp", "/images/step-04-delivery-kit.webp"],
    rating: 5.0, reviews: 2123, features: ["Free consult", "All categories", "No obligation"],
    badge: "Free consult", peakCategory: "longevity",
  }),
  item({
    slug: "cold-chain-shipping",
    name: "Priority Cold-Chain Shipping",
    tagline: "Temperature-sensitive meds",
    description: "Upgrade to priority cold-chain delivery for peptide and biologic orders.",
    longDescription: "Ensures temperature integrity from pharmacy to your door.",
    category: rc, categoryLabel: "Add-On", priceMonthly: 15,
    ...storeImg("delivery-kit"), rating: 4.9, reviews: 890, features: ["Cold chain", "Priority", "Peptides"],
    peakCategory: "muscle-recovery",
  }),
  item({
    slug: "injection-supplies-kit",
    name: "Injection Supplies Kit",
    tagline: "Syringes · alcohol · sharps",
    description: "Complete supply kit for injectable protocols.",
    longDescription: "Shipped with your first injectable order — refills available.",
    category: rc, categoryLabel: "Add-On", priceMonthly: 12,
    ...storeImg("peptide-kit"), rating: 4.8, reviews: 1456, features: ["Supplies", "Sharps container", "Refills"],
    peakCategory: "muscle-recovery",
  }),
];

export const CATEGORY_LABELS: Record<StoreCategory, string> = {
  "weight-loss": "Weight Loss",
  longevity: "Longevity",
  recovery: "Muscle Recovery",
  "mens-health": "Men's Health",
  "womens-health": "Women's Health",
  hair: "Hair",
  skincare: "Skincare",
  "sexual-wellness": "Sexual Wellness",
  sleep: "Sleep",
  "mental-health": "Mental Health",
  hormone: "Hormone",
};
